version:                "3"
services:
    datascience-notebook:
        image: jupyter/base-notebook
        build:
            context: .
          #  dockerfile: C:/Workspace/resume_testwork/test_task_syberry/doker/settings/Dockerfile
        volumes:
            - "C:/Workspace/resume_testwork/test_task_syberry/doker/settings:/home/jovyan/work"
        ports:
            - 8000:8888
        container_name:  python_yaml